import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import { Button } from "@/components/ui/button";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/ui/ThemeToggle";
import NavBar from "@/components/ui/NavBar";
import SideBar from "@/components/ui/SideBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="system"
            // enableSystem
            // disableTransitionOnChange
          >
            <div className="min-h-screen">
              <NavBar></NavBar>
              <main className="py-8">
                {/* content */}
                <div className="max-w-7xl mx-auto px-">
                  <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
                    <div className="hidden lg:block lg:col-span-3">
                      {/* Persons details */}
                      <SideBar></SideBar>
                    </div>
                    <div className="lg:col-span-9">{children}</div>
                    {/* <div className="lg:col-span-2">follow</div> */}
                  </div>
                </div>
              </main>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
